version: "3.8"
services:
    marketplace:
        environment:
            RECOMMENDATIONS_HOST: recommendations
        image: marketplace
        networks:
            - microservices
        ports:
            - 5000:5000

    recommendations:
        image: recommendations
        networks:
            - microservices
networks:
    microservices: